### ISSUE TITLE
Have you thought about the conversion between Swift and Objective-C?

### ISSUE THREAD

**Issue by LinMaris** [igorkulman/SwiftPascalInterpreter#23]
Have you thought about the conversion between Swift and Objective-C?

**Comment by igorkulman** [comment]
I am not sure what exactly you mean, re-writing the project from Swift to Objective-C? If so, no, not a chance :)

**Comment by LinMaris** [comment]
just like this 
https://github.com/LuizZak/SwiftRewriter

By AST.

**Comment by igorkulman** [comment]
The project you link is for rewriting Objective-C to Swift? What exactly are you trying to achieve?

**Comment by LinMaris** [comment]
OK, I understand what you mean, I recently researched how to convert Objective-C to Swift.
